config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweets

  resources :users

  root 'tweets#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /tweets
  def index
    @tweet = Tweet.new
    @tweets = Tweet.order("datetime(created_at) DESC").all
    @users = User.all
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: 'Rweet was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /tweets/1
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweets_path, notice: 'Rweet was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Rweet was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:edit, :update]
    before_action :authenticate_user!

    def edit
      if current_user.id === @user.id
        render 'edit'
      else
        redirect_to tweets_path
      end

    end

    def update
        if @user.update(user_params)
          redirect_to tweets_path, notice: 'User was successfully updated.'
        else
          render 'edit'
        end
    end

    
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:id, :email, :pseudo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rwitter</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>
  <body style="margin-top: 100px;">
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Rwitter</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= tweets_path %>">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <% if user_signed_in? %>
                <%= link_to 'Profile', edit_user_path(current_user.id), class: 'dropdown-item' %>
                <%= link_to 'logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              <% else %>
                <div class="dropdown-item">Please log-in</div>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid">
      <%= yield %>
    </div>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this rweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inline">
    <div class="form-group">
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.text_field :content, :class => 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.submit 'Rweet', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/tweets/_jumbo.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <div class="img"></div>
    <div class="container">
      <h1 class="display-3">Rwitter</h1>
      <p>Simple Twitter like app on Rails</p>
      <p><%= render 'form', tweet: @tweet %></p>
    </div>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Rweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<%= render 'jumbo' %>

<div class="row">
  
    <% @tweets.each do |tweet| %>
    <div class="col-sm-4">
      <div class="card">
        <h4 class="card-header bg-primary">
        <div class="inline" style="color: white;">
            <% if tweet.user.pseudo.nil? && current_user.id == tweet.user_id %>
              <%= link_to "Add pseudo", edit_user_path(tweet.user.id) %>
            <% else %>
              @<%= tweet.user.pseudo %>
            <% end %>
        </div>
        </h4>
        <div class="card-block">
          <h5 class="card-title">
            <% if current_user.id == tweet.user_id %>
              <td><%= link_to "#{tweet.content}", edit_tweet_path(tweet) %></td>
            <% else %>
              <td><%= tweet.content %></td>
            <% end %>
          </h5>
          <p class="card-text">
            posted <%= time_ago_in_words(tweet.created_at) %> ago
          </p>
          <% if current_user.id == tweet.user_id %>
            <%= link_to 'Remove rweet', tweet, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.hidden_field :id, :value => current_user.id %>
      <p>
        <%= f.label :pseudo %>
        <%= f.text_field :pseudo, :class => 'form-control text' %>
      </p>
      <p>
        <%= f.label :email %>
        <%= f.text_field :email, :class => 'form-control email'  %>
      </p>
      <p>
        <%= f.submit 'Update', :class => 'btn btn-primary' %>
      </p>
    </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
    <h1>Edit your profile</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Back', tweets_path %>
</div>